package boikoro.marsrovers;

public class Position {
	final private int xPosition;
	final private int yPosition;
	final String direction;
	

	public Position(int xPosition, int yPosition, String direction) {
		this.xPosition = xPosition;
		this.yPosition = yPosition;
		this.direction = direction;
	}

	public Position getCopy() {
		return new Position(xPosition, yPosition, direction);
	}

	@Override
	public boolean equals(Object other) {
		Position otherPosition = (Position) other;
		return (this.xPosition == otherPosition.xPosition)
				&& (this.yPosition == otherPosition.yPosition)
				&& this.direction.equals(otherPosition.direction);
	}

	@Override//Autogenerated
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((direction == null) ? 0 : direction.hashCode());
		result = prime * result + xPosition;
		result = prime * result + yPosition;
		return result;
	}
}
