package boikoro.marsrovers;

import static boikoro.marsrovers.Direction.turnDirection;
import static java.lang.String.format;

public class Position {
	private final int xPosition;
	private final int yPosition;
	private final String direction;

	public Position(int xPosition, int yPosition, String direction) {
		this.xPosition = xPosition;
		this.yPosition = yPosition;
		this.direction = direction;
	}

	public String direction() {
		return this.direction;
	}

	public Position getCopy() {
		return new Position(xPosition, yPosition, direction);
	}

	@Override
	public boolean equals(Object other) {
		Position otherPosition = (Position) other;
		return (this.xPosition == otherPosition.xPosition)
				&& (this.yPosition == otherPosition.yPosition)
				&& this.direction.equals(otherPosition.direction);
	}

	@Override//Autogenerated
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((direction == null) ? 0 : direction.hashCode());
		result = prime * result + xPosition;
		result = prime * result + yPosition;
		return result;
	}

	public Position nextPosition(String step) {
		if (step.equals(Step.MOVE)) {
			if (direction.equals(Direction.SOUTH)) {
				return new Position(xPosition, yPosition - 1, direction);
			} else if (direction.equals(Direction.WEST)) {
				return new Position(xPosition - 1, yPosition, direction);
			} else if (direction.equals(Direction.NORTH)) {
				return new Position(xPosition, yPosition + 1, direction);
			} else if (direction.equals(Direction.EAST)) {
				return new Position(xPosition + 1, yPosition, direction);
			}
		}

		return new Position(xPosition, yPosition, turnDirection(direction, step));
	}

	@Override
	public String toString() {
		return format("Position(x=%d, y=%d, direction=%s)", xPosition, yPosition, direction);
	}
	
	

}
